---
title: "R Notebook"
output: html_notebook
---

```{r}
library("readxl")
library("tidyverse")
require("tidyverse")
library("writexl")
library("tibble")
library("openxlsx")
library("DBI")
library("odbc")
library("RSQLite")
library("psych")
library("pracma")
library("bit64")
library('glue')
library('RMySQL')
library('stringi')
library('rlang')

source("func_test.R")
```

#### 1. Importacion de las bases de datos

Se importa la base de datos, y el catalogo del ipp con sus ponderaciones

```{r}

ponderaciones <- read_excel("catalogoIPP_test.xlsx", sheet = "Sheet1") %>% 
  mutate(VARIEDAD = gsub("\\.", "", VARIEDAD)) %>% 
  rename(PRODUCTO = VARIEDAD, ponderacion = `Ponderacion 5 Digitos`) %>% 
  mutate(
    ACTIVIDAD = substr(PRODUCTO, 1, 6),
    CLASE = substr(PRODUCTO, 1, 5),
    GRUPO = substr(PRODUCTO, 1, 4),
    GRUPO = substr(PRODUCTO, 1, 4),
    DIVISION = substr(PRODUCTO, 1, 3),
    SECCION = substr(PRODUCTO, 1, 1)
  )
```

```{r}
mes <- 1

variables <- inputdata(mes)

mes <- variables$mes
mesant <- variables$mes_ant

mes
mesant
```

```{r}
#se importan los indices anteriores
file_name <- paste0("ind_", mesant, ".xlsx")
indant <- read_excel(file_name, sheet = "Sheet1") %>% 
  mutate(PRODUCTO = gsub("\\.", "", PRODUCTO))
```

```{r}
#se importan los precios actuales
precios <- read_excel("precios_test.xlsx", sheet = "Sheet1") %>% 
  mutate(ACTIVIDAD = gsub("\\.", "", ACTIVIDAD),
         PRODUCTO = gsub("\\.", "", PRODUCTO),
         VARIEDAD = gsub("\\.", "", VARIEDAD))

boleta <- precios %>% 
  select(PRODUCTO, VARIEDAD, all_of(mes), all_of(mesant)) %>% 
  mutate(!!mesant := if_else(!!sym(mesant) == 0, !!sym(mes), !!sym(mesant))) %>% 
  filter(!!sym(mesant) != 0) %>% 
  filter(!!sym(mes) != 0) #tuve que quitar las filas que tienen valor 0 en el mes anterior y en el mes actual (por el momento)
```

#### 2. Calculo del IPP

##### 2.1 Relativo de precios de las variedades

```{r}
relativo_var <- boleta %>% 
  mutate(rel_var = !!sym(mes) / !!sym(mesant)) %>% 
  drop_na(PRODUCTO)
```

##### 2.2 Indice del producto

```{r}
#esto seria lo que en el manual de cepal 
ind_var <- relativo_var %>% group_by(PRODUCTO) %>% 
  summarize(rel_prod = geometric.mean(rel_var))
```

```{r}
ind_prod <- ind_var %>% left_join(indant %>% select(PRODUCTO, indice), by = join_by(PRODUCTO)) %>% 
  rename(indant = indice) %>% 
  mutate(indice = indant*rel_prod) %>% 
  drop_na(indice) #le puse este drop na por ahora ya que en el indice de enero no estan todos los productos

ind_prod01 <- ind_prod %>% 
  select(PRODUCTO, indice)
```

##### 2.2 Indice de agregaciones superiores a producto

```{r}
calc_indx(ACTIVIDAD)
calc_indx(CLASE)
calc_indx(GRUPO)
calc_indx(DIVISION)
calc_indx(SECCION) #este seria el indice general
```

```{r}
wb <- createWorkbook()
 
addWorksheet(wb, "Sheet1")
writeData(wb, "Sheet1", ind_prod01)
 
file_name <- paste0("ind_", mes, ".xlsx")
saveWorkbook(wb, file_name, overwrite = TRUE)
```

\*Voy a revisar que productos son los que no hay precios anteriores

```{r}
#esta seria una lista de productos que si se podrian imputar porque tienen 3 o mas variedades
can_imput <- c('C101041', 'C103011', 'C103012', 'C103013', 'C103014', 'C104011', 'C105012', 'C106111', 'C106131', 'C106211', 'C107112', 'C107311', 'C107511', 'C107911', 'C108011', 'C110111', 'C110211', 'C110411', 'C131211', 'C139211', 'C141011', 'C151211', 'C152011', 'C161011', 'C162111', 'C170911', 'C170211', 'C201121', 'C201211', 'C202111', 'C202211', 'C202311', 'C202911', 'C210011', 'C222011', 'C231011', 'C239211', 'C239212', 'C239511', 'C239611', 'C239911', 'C241011', 'C259911', 'C281911', 'C310011', 'C322111', 'C323011', 'C329011')
```

```{r}
#aqui encuentro cuales son los productos que se pierden debido a problemas con los precios anteriores
missing_prod <- ponderaciones %>% select(CCP...1, PRODUCTO, ponderacion) %>% 
  filter(CCP...1 == 'PRODUCTO') %>% anti_join(ind_prod, by='PRODUCTO')
missing_prod
```

```{r}
#aqui encuentro cuales de los precios que no estan SI se pueden imputar porque son de los que si hay 3 o mas variedades
missing_prod %>% filter(PRODUCTO %in% can_imput)
```

```{r}
#aqui encuentro los precios que no estan y que NO se pueden imputar, por lo que segun mi idea se les podria poner un rel=1 en el primer paso
missing_prod %>% filter(!(PRODUCTO %in% can_imput))
```

```{r}
boleta %>% filter(!!sym(mes) == 0)
```

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

```{r}
list_prod_prices <- precios %>% select(PRODUCTO, !!sym(mes)) %>% distinct(PRODUCTO) %>% drop_na() #por esto solamente me salen 90 productos con indices, no se tienen datos de todos los productos :c
list_prod_prices
```

```{r}
list_prod <- ponderaciones %>% select(CCP...1, DESCRIPCION, PRODUCTO) %>% filter(CCP...1 == 'PRODUCTO') 
list_prod
```

```{r}
#list_prod_prices %>% filter(!(PRODUCTO %in% list_prod))

list_prod %>% anti_join(list_prod_prices, by='PRODUCTO') %>% select(PRODUCTO, DESCRIPCION)
#estos son los productos de la canasta que no estan en los precios recolectados
```

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

```{r}
## ESTA FUNCION SE USARIA SI TUVIERAMOS EL AÑO TAMBIEN EN EL EXCEL PERO COMO NO, ENTONCES NO VAMOS A PONER EL AÑO
# inputdata <- function(month_number) {
#   month_names <- c("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")
#   
#   if (month_number < 1 || month_number > 12) {
#     stop("Por favor ingresar numero entre 1 y 12.")
#   }
#   
#   mes <- month_names[month_number]
#   
#   # Calculate the previous month
#   if (month_number == 1) {
#     mes_ant <- list(mes = month_names[12], year_shift = -1)
#   } else {
#     mes_ant <- list(mes = month_names[month_number - 1], year_shift = 0)
#   }
#   
#   colstorename <- 2:(month_number + 1)
#   
#   months <- month_names[1:month_number]
#   
#   col_indices <- c(1, seq(2, 2 * month_number, by = 2))
#   
#   return(list(mes = mes, mes_ant = mes_ant, colstorename = colstorename, months = months, col_indices = col_indices))
# }
```

```{r}
#funcion para ingresar los datos
# inputdata <- function(month_number) {
#   month_names <- c("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")
#   
#   if (month_number < 1 || month_number > 12) {
#     stop("Por favor ingresar numero entre 1 y 12.")
#   }
#   
#   mes <- month_names[month_number]
#   
#   if (month_number == 1) {
#     mes_ant <- month_names[12]
#   }
#   else {
#     mes_ant <- month_names[month_number - 1]
#   }
#   
#   colstorename <- 2:(month_number + 1)
#   
#   months <- month_names[1:month_number]
#   
#   col_indices <- c(1, seq(2, 2 * month_number, by = 2))
#   
#   return(list(mes = mes, mes_ant = mes_ant, colstorename = colstorename, months = months, col_indices = col_indices))
# }
# 
# mes <- 1
# 
# inputdata(mes)
```

#### 
